workdir: /data/iacobuzc/haochen/condor_pipeline_trial
sample_name_map: /data/iacobuzc/haochen/Tapestri_main_manuscript_analysis/Tapestri_batch2_samples_MASTER_INTERNAL.xlsx
patients:
  - PC01
  - PC02
  - PC03
  - PC04
  - PC05
  - PC06
  - PC07
  - PC08
  - PC09
  - PC10
  - PC11
  - PC12
  - PC13
  - PC14
  - PC15
  - PC16 # ETE tree had some issue so had to be rerun
  - PC17
  - PC18
  - PC19
  - PC20
  - PC21
  - PC22
  - PC23 # need to be run separately as it requires lots of memory
  - PC24

# ===== centralized data directory =====
raw_data_directory: /data/iacobuzc/haochen/Tapestri_main_manuscript_analysis/data_compiled/fillout_h5
# this directory should be in the following structure:
#  - {patient_1}.*.h5
#  - {patient_2}.*.h5
annotated_mutations: /lila/data/iacobuzc/haochen/Tapestri_main_manuscript_analysis/data_compiled/manual_annotated_snv_lists
# this directory should be in the following structure:
#  - {patient_1}*voi.hz_curated.txt
#  - {patient_2}*voi.hz_curated.txt
falcon_solutions: /data/iacobuzc/haochen/Tapestri_main_manuscript_analysis/data_compiled/falcon_solutions
# this directory should be in the following structure:
# - {patient_1}*assignment*.csv
# - {patient_1}*clone_profile*.csv
# - {patient_2}*assignment*.csv
# - {patient_2}*clone_profile*.csv
subclonal_mutations: /data/iacobuzc/haochen/Tapestri_main_manuscript_analysis/data_compiled/manual_subclonal_snvs
# THIS PATH MUST EXIST, BUT NOT EVERY PATIENT MUST HAVE A FILE. But if there should be one, it should be named:
# - {patient_1}.subclonal_mutations.yaml

# ===== scripts and params =====
amplicon_coordinates_file: /data/iacobuzc/haochen/Tapestri_batch2/analysis/full-ConDoR/references/panel3559_analysis.gene_cytoband.formatted.manual_adjusted.gene_pos_ado_added.csv
condor_pipeline_scripts_dir: /data/iacobuzc/haochen/Tapestri_batch2/analysis/full-ConDoR/scripts
fast_condor_script: /data/iacobuzc/haochen/Tapestri_batch2/analysis/full-ConDoR/fast-ConDoR/src/fast-condor.py
condor_downstream_scripts_dir: /data/iacobuzc/haochen/Tapestri_batch2/analysis/full-ConDoR/condor_downstream
tap_cn_call_plot_script: /data/iacobuzc/haochen/Tapestri_project/tap_cn_calling/scripts/PLOT-unique_cn_profiles.py # <--- point this to tap_cn_call directory